version: '2.1'
services:

  user-db:
    build:
      context: ./user-db/
    image: kannji_user-db
    env_file:
      - ./env/user-db.env
    environment:
      - POSTGRES_USER=${USER_DB_USER}
      - POSTGRES_PASSWORD=${USER_DB_PASSWORD}
      - POSTGRES_DB=${USER_DB_DBNAME}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 15
    networks:
      - user
    volumes:
      - ./user-db/data/:/var/lib/postgresql/data/

  user-server:
    build:
      context: ./user-server/
    image: kannji_user-server
    env_file:
      - ./env/user-db.env
      - ./env/user-server.env
      - ./env/nginx.env
      - ./env/global.env
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - user
      - nginx

  nginx:
    build:
      context: ./nginx/
    image: kannji_nginx
    env_file:
      - ./env/nginx.env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx
    depends_on:
      - user-server

networks:
  user:
  nginx: